---
language: python

services:
  - docker

before_install: 
  - docker pull mitermayer/vim-test-bed

script: 
  - docker run --rm -v $PWD:/testplugin -v $PWD/tests:/home "mitermayer/vim-test-bed" vint testplugin 
  - docker run --rm --entrypoint=/bin/bash -v $PWD:/testplugin -v $PWD/tests:/home "mitermayer/vim-test-bed" -s npm install && npm test
