---
language: python

services:
  - docker

before_install: 
  - docker pull mitermayer/vim-test-bed

script: 
  - docker run --rm -v $PWD:/testplugin -v $PWD/test:/home "mitermayer/vim-test-bed" vint testplugin 
